common_nouns = [
    "time", "year", "people", "way", "day", "man", "thing", "woman",
    "life", "child", "world", "school", "state", "family", "student",
    "group", "country", "problem", "hand", "part", "place", "case",
    "group", "fact", "eye", "friend", "month", "truth", "morning",
    "idea", "death", "government", "company", "team", "minute",
    "law", "car", "city", "community", "name", "face", "job", "book",
    "room", "friend", "question", "home", "business", "information",
    "body", "area", "money", "story", "young", "fact", "month", "lot",
    "right", "study", "book", "eye", "job", "word", "business", "issue",
    "side", "kind", "head", "house", "service", "friend", "father",
    "power", "hour", "game", "line", "end", "member", "law", "car",
    "city", "community", "name", "president", "team", "minute", "idea",
    "kid", "body", "information", "back", "parent", "face", "others",
    "level", "office", "door", "health", "person", "art", "war", "history",
    "party", "result", "change", "morning", "reason", "research", "girl",
    "guy", "moment", "air", "teacher", "force", "education", "foot", "boy",
    "age", "policy", "food", "way", "heart", "therapy", "music", "management",
    "safety", "term", "voice", "boy", "sun", "death", "region", "arm", "nature",
    "bird", "literature", "software", "data", "difference", "calculus", "variable",
    "energy", "fire", "position", "blood", "chapter", "teacher", "mother", "quality",
    "procedure", "environment", "wood", "river", "choice", "practice", "government",
    "market", "sense", "building", "capital", "church", "address", "event", "matter",
    "center", "value", "method", "movie", "meeting", "communication", "driver",
    "structure", "role", "development", "week", "category", "soldier", "expression",
    "importance", "manager", "owner", "machine", "model", "opinion", "theory",
    "growth", "status", "knowledge", "reality", "computer", "college", "boat",
    "object", "cell", "industry", "variety", "material", "occasion", "purpose",
    "editor", "effort", "presentation", "score", "mass", "experiment", "engine",
    "customer", "response", "operation", "election", "character", "population",
    "technology", "attention", "movement", "distance", "security", "feeling",
    "standard", "activity", "society", "congress", "element", "vision", "damage",
    "basis", "instance", "discussion", "conflict", "option", "credit", "characteristic",
    "network", "victory", "communication", "performance", "revenue", "definition",
    "interpretation", "anxiety", "atmosphere", "negotiation", "obligation", "recognition",
    "judgment", "series", "attention", "committee", "progress", "employment", "style",
    "adult", "attitude", "religion", "strategy", "design", "impact", "function",
    "resource", "concept", "budget", "analysis", "examination", "theme", "leadership",
    "recommendation", "mall", "advantage", "novel", "significance", "action", "tradition",
    "skill", "individual", "medicine", "sector", "rule", "fight", "application",
    "responsibility", "focus", "theory", "surgery", "description", "difference", "goal",
    "revenue", "return", "earth", "investment", "property", "condition", "decision",
    "street", "industry", "meaning", "foundation", "importance", "extent", "unit", "agency",
    "director", "debate", "citizen", "profit", "program", "commission", "contract", "tradition",
    "culture", "medium", "project", "link", "definition", "reform", "survey", "teacher",
    "suggestion", "organization", "consequence", "initiative", "impression", "university", "argument",
    "speaker", "radio", "peace", "permission", "influence", "potential", "review", "explanation",
    "campus", "victim", "newspaper", "threat", "commitment", "democracy", "direction", "conference",
    "opportunity", "audience", "fishing", "consideration", "opposition", "bottle", "garden", "collection",
    "republic", "suggestion", "failure", "reflection", "appointment", "document", "expression", "equipment",
    "sight", "occasion", "display", "symptom", "matter", "procedure", "interaction", "connection",
    "support", "intention", "association", "promise", "failure", "panel", "technique", "mood",
    "dialogue", "register", "distinction", "reputation", "summit", "athlete", "farm", "appeal",
    "shadow", "negotiation", "trainer", "sympathy", "empire", "contribution", "approach", "importance",
    "fruit", "bedroom", "employment", "prospect", "competition", "claim", "journalist", "gift",
    "estate", "mirror", "interview", "application", "background", "perspective", "conviction", "aspect",
    "emotion", "scene", "figure", "mission", "climate", "county",
    "union", "marriage", "stock", "failure", "classroom", "device",
    "freedom", "paper", "weight", "height", "journey", "quality",
    "reaction", "solution", "sugar", "admission", "attitude",
    "director", "personality", "muscle", "song", "liquid", "camera",
    "headache", "ladder", "decision", "anxiety", "chapter", "fortune",
    "baby", "residence", "document", "application", "organization",
    "division", "furniture", "tooth", "corridor", "duty", "brain",
    "texture", "medium", "platform", "stranger", "gene", "package",
    "flight", "scenario", "pollution", "emergency", "profit", "appointment",
    "chemistry", "parliament", "situation", "arrival", "purchase", "sanction",
    "molecule", "tourist", "lighting", "injury", "identity", "perception",
    "spectrum", "signal", "vessel", "guitar", "recession", "cousin",
    "mortgage", "concept", "diagnosis", "performance", "indication",
    "cigarette", "scholar", "settlement", "layer", "subsidiary", "capability",
    "operation", "restaurant", "inflation", "alternative", "microscope",
    "domain", "portion", "equation", "landscape", "cycle", "prescription",
    "adaptation", "measurement", "settlement", "consumer", "confidence",
    "consultation", "currency", "guidance", "mechanism", "variation",
    "transfer", "contradiction", "brother", "insight", "interpretation",
    "climate", "boyfriend", "composition", "initiative", "technique",
    "penalty", "portfolio", "rival", "stake", "fiber", "activist",
    "terrorism", "refugee", "hypothesis", "ministry", "vaccine",
    "spin", "controller", "ownership", "scholarship", "reform", "regulation",
    "standard", "strategy", "discipline", "referral", "distinction", "integrity",
    "exposure", "dilemma", "dignity", "psychology", "convention", "threshold",
    "mountain", "widget", "arena", "grain", "colleague", "franchise", "microphone",
    "banner", "latitude", "longitude", "spectacle", "tunnel", "maze",
    "puzzle", "ledger", "manuscript", "fossil", "sponsor", "philosopher",
    "ambassador", "dynamo", "artifact", "parameter", "bluff", "nominee",
    "quota", "volcano", "zoo", "memo", "byte", "genre", "quota", "vector", "lava",
    "king", "queen", "person", "privilege", "wealth", "monarch", "power", "history", "ruler", "kingdom",
    "people", "monarchy", "prince", "son", "family", "brother", "sister", "princess", "daughter", "son",
    "insect", "fly", "thought", "rationality", "eruption", "flow", "explosion", "bomb",
    "religion", "war", "peace", "park", "animal", "mammal", "reptile", "bird", "fish", "amphibian", "insect",
    "human", "religion", "god",
    "christmas", "easter", "holiday", "celebration", "tradition", "culture",
     "zen", "bible", "torah", "quran", "prayer", "church",
    "chair", "table", "kitchen", "cake", "lunch", "sadness", "joy", "vegetable", "horror", "birth", "tree",
    "plant", "volume", "green", "red", "couple"
]
